logoutput: stdout
errorlog: stderr

# Listen on all interfaces, port 1080
internal: 0.0.0.0 port = 1080
external: eth0

# Use password-file method
socksmethod: username
user.privileged: root
user.notprivileged: nobody

# Rules will be added here by the entrypoint script
