#!/bin/bash

set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output

echo "-----> Running post-compile script"

# Remove all the files we don't need
rm -rf src deploy/python-uv deploy/env .cursor .github compose.yaml README.md .cache

chmod +x deploy/paas/scalingo_run_web