# Generated by Django 5.1.8 on 2025-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mime_id',
            field=models.CharField(blank=True, max_length=998, null=True, unique=True, verbose_name='mime id'),
        ),
    ]
