# Generated by Django 5.1.8 on 2025-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='is_unread',
            field=models.BooleanField(default=False, verbose_name='is unread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='count_draft',
            field=models.IntegerField(default=0, verbose_name='count draft'),
        ),
        migrations.AddField(
            model_name='thread',
            name='count_sender',
            field=models.IntegerField(default=0, verbose_name='count sender'),
        ),
        migrations.AddField(
            model_name='thread',
            name='count_starred',
            field=models.IntegerField(default=0, verbose_name='count starred'),
        ),
        migrations.AddField(
            model_name='thread',
            name='count_trashed',
            field=models.IntegerField(default=0, verbose_name='count trashed'),
        ),
        migrations.AddField(
            model_name='thread',
            name='count_unread',
            field=models.IntegerField(default=0, verbose_name='count unread'),
        ),
    ]
