# Generated by Django 5.1.8 on 2025-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_message_is_read_remove_thread_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='count_messages',
            field=models.IntegerField(default=1, verbose_name='count messages'),
        ),
        migrations.AddField(
            model_name='thread',
            name='messaged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='messaged at'),
        ),
    ]
