# Generated by Django 5.1.8 on 2025-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_mime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxaccess',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('edit', 'Edit'), ('send', 'Send'), ('delete', 'Delete'), ('admin', 'Admin')], default='read', max_length=20, verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('message', 'contact', 'type')},
        ),
    ]
