# Generated by Django 5.1.8 on 2025-07-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_message_draft_body_message_draft_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_attachments',
            field=models.BooleanField(default=False, verbose_name='has attachments'),
        ),
    ]
