# Generated by Django 5.1.8 on 2025-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_thread_count_messages_thread_messaged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='sender_names',
            field=models.JSONField(default=list, verbose_name='sender names'),
        ),
    ]
