# Generated by Django 5.1.8 on 2025-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mailboxaccess_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='is draft'),
        ),
    ]
