# Generated by Django 5.1.8 on 2025-04-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_message_read_at_alter_message_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='raw_mime',
            field=models.TextField(default='', verbose_name='raw message'),
            preserve_default=False,
        ),
    ]
