# Generated by Django 5.1.8 on 2025-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_thread_sender_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='sender_names',
            field=models.JSONField(blank=True, null=True, verbose_name='sender names'),
        ),
    ]
