# Generated by Django 5.1.8 on 2025-04-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_raw_mime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='raw_mime',
            field=models.TextField(blank=True, verbose_name='raw message'),
        ),
    ]
