# Generated by Django 5.1.8 on 2025-04-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='draft_body',
            field=models.TextField(blank=True, verbose_name='draft body'),
        ),
    ]
