# Generated by Django 5.1.8 on 2025-04-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_message_raw_mime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.mailbox'),
        ),
    ]
