# Generated by Django 5.1.8 on 2025-05-02 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_thread_sender_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='mailbox',
        ),
        migrations.CreateModel(
            name='ThreadAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=20, verbose_name='role')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_accesses', to='core.mailbox')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='core.thread')),
            ],
            options={
                'verbose_name': 'thread access',
                'verbose_name_plural': 'thread accesses',
                'db_table': 'messages_threadaccess',
                'unique_together': {('thread', 'mailbox')},
            },
        ),
    ]
