# Generated by Django 5.1.8 on 2025-08-20 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_label_description_label_is_auto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(help_text="Name of the template (e.g., 'Standard Reply', 'Out of Office', 'Work Signature')", max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Optional description of when to use this template', verbose_name='description')),
                ('html_body', models.TextField(blank=True, help_text="HTML email body template with placeholders (e.g., '<p>Dear {recipient_name},</p>') or signature content", verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, help_text="Plain text email body template with placeholders (e.g., 'Dear {recipient_name},') or signature content", verbose_name='text body')),
                ('kind', models.SmallIntegerField(choices=[(1, 'reply'), (2, 'new_message'), (3, 'signature')], default=1, help_text='Kind of template (reply, forward, new message, auto reply, signature)', verbose_name='kind')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use', verbose_name='is active')),
            ],
            options={
                'verbose_name': 'message template',
                'verbose_name_plural': 'message templates',
                'db_table': 'messages_messagetemplate',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='maildomain',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata to sync to the maildomain group in the identity provider.', verbose_name='Custom attributes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata to sync to the user in the identity provider.', verbose_name='Custom attributes'),
        ),
        migrations.CreateModel(
            name='MessageTemplateMailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this template is the default for this mailbox', verbose_name='is default')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_mailboxes', to='core.mailbox')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_mailboxes', to='core.messagetemplate')),
            ],
            options={
                'verbose_name': 'message template mailbox',
                'verbose_name_plural': 'message template mailboxes',
                'db_table': 'messages_messagetemplatemailbox',
                'unique_together': {('template', 'mailbox')},
            },
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='mailboxes',
            field=models.ManyToManyField(help_text='Mailboxes that can use this template', related_name='message_templates', through='core.MessageTemplateMailbox', to='core.mailbox'),
        ),
        migrations.CreateModel(
            name='MessageTemplateMailDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this template is the default for this mail domain', verbose_name='is default')),
                ('maildomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_maildomains', to='core.maildomain')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_maildomains', to='core.messagetemplate')),
            ],
            options={
                'verbose_name': 'message template mail domain',
                'verbose_name_plural': 'message template mail domains',
                'db_table': 'messages_messagetemplatemaildomain',
                'unique_together': {('template', 'maildomain')},
            },
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='maildomains',
            field=models.ManyToManyField(help_text='Mail domains that can use this template', related_name='message_templates', through='core.MessageTemplateMailDomain', to='core.maildomain'),
        ),
    ]
