# Generated by Django 5.1.8 on 2025-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_thread_sender_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mta_sent',
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered at'),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='delivery_message',
            field=models.TextField(blank=True, null=True, verbose_name='delivery message'),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('internal', 'Internal'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry')], max_length=20, null=True, verbose_name='delivery status'),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retry at'),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='retry count'),
        ),
    ]
