# Generated by Django 5.1.8 on 2025-05-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_message_mta_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='alias_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mailbox'),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='alias_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maildomain'),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='oidc_autojoin',
            field=models.BooleanField(default=False, help_text='Create mailboxes automatically based on OIDC emails.', verbose_name='oidc autojoin'),
        ),
        migrations.AlterField(
            model_name='maildomain',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry')], max_length=20, null=True, verbose_name='delivery status'),
        ),
    ]
