# Generated by Django 5.1.8 on 2025-08-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_messagetemplate_alter_maildomain_custom_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='raw_blob',
            field=models.ForeignKey(blank=True, help_text='Reference to the blob containing raw template data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to='core.blob'),
        ),
    ]
