# Generated by Django 5.1.8 on 2025-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_thread_mailbox_threadaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailboxaccess',
            unique_together={('mailbox', 'user')},
        ),
        migrations.AddField(
            model_name='mailboxaccess',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=20, verbose_name='role'),
        ),
        migrations.RemoveField(
            model_name='mailboxaccess',
            name='permission',
        ),
    ]
