# Generated by Django 5.1.8 on 2025-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='message',
            name='body_text',
        ),
        migrations.AlterField(
            model_name='message',
            name='raw_mime',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
