# Generated by Django 5.1.12 on 2025-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_messagetemplate_blob_maildomain_alter_blob_mailbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='size_compressed',
            field=models.PositiveIntegerField(default=0, help_text='Size of the compressed blob in bytes', verbose_name='compressed size'),
            preserve_default=False,
        ),
    ]
