# Generated by Django 5.1.8 on 2025-08-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_messagetemplate_raw_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='mailbox',
            field=models.ForeignKey(blank=True, help_text='Mailbox that owns this blob', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='core.mailbox'),
        ),
    ]
