# Generated by Django 5.1.8 on 2025-04-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_message_body_html_remove_message_body_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
