# Generated by Django 5.1.8 on 2025-05-13 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mailbox_alias_of_maildomain_alias_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('sha256', models.CharField(db_index=True, help_text='SHA-256 hash of the attachment content', max_length=64, verbose_name='sha256 hash')),
                ('size', models.PositiveIntegerField(help_text='Size of the attachment in bytes', verbose_name='file size')),
                ('name', models.CharField(help_text='Original filename of the attachment', max_length=255, verbose_name='file name')),
                ('content_type', models.CharField(help_text='MIME type of the attachment', max_length=255, verbose_name='content type')),
                ('raw_content', models.BinaryField(help_text='Binary content of the attachment, will be offloaded to object storage in the future', verbose_name='raw content')),
                ('mailbox', models.ForeignKey(help_text='Mailbox that owns this attachment', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.mailbox')),
                ('messages', models.ManyToManyField(help_text='Messages that use this attachment', related_name='attachments', to='core.message')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'db_table': 'messages_attachment',
                'ordering': ['-created_at'],
            },
        ),
    ]
