# Generated by Django 5.1.12 on 2025-10-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_messagetemplate_blob_maildomain_alter_blob_mailbox_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email', 'mailbox', 'name')},
        ),
    ]
