# Generated by Django 5.1.8 on 2025-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
    ]
