# Generated by Django 5.1.8 on 2025-05-13 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='raw_content',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='sha256',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='size',
        ),
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('sha256', models.CharField(db_index=True, help_text='SHA-256 hash of the blob content', max_length=64, verbose_name='sha256 hash')),
                ('size', models.PositiveIntegerField(help_text='Size of the blob in bytes', verbose_name='file size')),
                ('type', models.CharField(help_text='MIME type of the blob', max_length=255, verbose_name='content type')),
                ('raw_content', models.BinaryField(help_text='Binary content of the blob, will be offloaded to object storage in the future', verbose_name='raw content')),
                ('mailbox', models.ForeignKey(help_text='Mailbox that owns this blob', on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='core.mailbox')),
            ],
            options={
                'verbose_name': 'blob',
                'verbose_name_plural': 'blobs',
                'db_table': 'messages_blob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='blob',
            field=models.ForeignKey(default='', help_text='Reference to the blob containing the attachment data', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.blob'),
            preserve_default=False,
        ),
    ]
