# Generated by Django 5.1.13 on 2025-11-02 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_messagetemplate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('type', models.CharField(max_length=36, verbose_name='type')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('channel', models.ForeignKey(blank=True, help_text='Channel that created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_events', to='core.channel')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.thread')),
            ],
            options={
                'verbose_name': 'thread event',
                'verbose_name_plural': 'thread events',
                'db_table': 'messages_threadevent',
                'ordering': ['created_at'],
            },
        ),
    ]
