# Generated by Django 5.1.8 on 2025-05-19 15:16

import django.db.models.deletion
from django.db import migrations, models

def migrate_mailbox_contacts(apps, schema_editor):
    Mailbox = apps.get_model('core', 'Mailbox')
    Contact = apps.get_model('core', 'Contact')
    for mailbox in Mailbox.objects.filter(contact__isnull=True):
        mailbox.contact = Contact.objects.create(email=str(mailbox), mailbox=mailbox)
        mailbox.save()

def reverse_migrate_mailbox_contacts(apps, schema_editor):
    Mailbox = apps.get_model('core', 'Mailbox')
    for mailbox in Mailbox.objects.filter(contact__isnull=False):
        mailbox.contact = None
        mailbox.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS unaccent;', 'DROP EXTENSION IF EXISTS unaccent;'),
        migrations.AddField(
            model_name='mailbox',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='core.contact'),
        ),
        migrations.RunPython(
            code=migrate_mailbox_contacts,
            reverse_code=reverse_migrate_mailbox_contacts,
        ),
    ]
