# Generated by Django 5.1.8 on 2025-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
