# Generated by Django 5.1.13 on 2025-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_language_inboundmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='custom_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom settings for the mail domain.', verbose_name='Custom settings'),
        ),
    ]
