# Generated by Django 5.1.13 on 2025-12-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_thread_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='custom_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom settings for the mailbox.', verbose_name='Custom settings'),
        ),
    ]
