# Generated by Django 5.1.8 on 2025-05-21 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_maildomainaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='local_part',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_.-]+$')], verbose_name='local part'),
        ),
    ]
