# Generated by Django 5.1.8 on 2025-06-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mailbox_local_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='identity_group_metadata',
            field=models.JSONField(default=None, help_text='Metadata to sync to the maildomain group in the identity provider.', verbose_name='Metadata to sync to the maildomain group in the identity provider'),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='identity_sync',
            field=models.BooleanField(default=False, help_text='Sync mailboxes to identity provider.', verbose_name='Identity sync'),
        ),
    ]
