# Generated by Django 5.1.8 on 2025-06-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_maildomain_identity_group_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='count_draft',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='count_messages',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='count_sender',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='count_starred',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='count_trashed',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='count_unread',
        ),
        migrations.AddField(
            model_name='message',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='archived at'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='is archived'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='is spam'),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_active',
            field=models.BooleanField(default=False, verbose_name='has active'),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_draft',
            field=models.BooleanField(default=False, verbose_name='has draft'),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_messages',
            field=models.BooleanField(default=True, verbose_name='has messages'),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_sender',
            field=models.BooleanField(default=False, verbose_name='has sender'),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_starred',
            field=models.BooleanField(default=False, verbose_name='has starred'),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_trashed',
            field=models.BooleanField(default=False, verbose_name='has trashed'),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_unread',
            field=models.BooleanField(default=False, verbose_name='has unread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='is spam'),
        ),
    ]
