# Generated by Django 5.1.8 on 2025-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_maildomain_identity_group_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildomain',
            name='identity_group_metadata',
            field=models.JSONField(blank=True, default=None, help_text='Metadata to sync to the maildomain group in the identity provider.', null=True, verbose_name='Metadata to sync to the maildomain group in the identity provider'),
        ),
    ]
