# Generated by Django 5.2.11 on 2026-04-01 17:05

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_threadevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='encrypted_settings',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict, help_text='Encrypted channel settings (e.g., app-specific passwords)', verbose_name='encrypted settings'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this channel (used for permissions and auditing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
