# Generated by Django 5.2.11 on 2026-04-01 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_threadevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('type', models.CharField(max_length=36, verbose_name='type')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.thread')),
                ('thread_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.threadevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user notification',
                'verbose_name_plural': 'user notifications',
                'db_table': 'messages_usernotification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_done', '-created_at'], name='notif_user_done_created_idx')],
            },
        ),
    ]
