# Generated by Django 5.2.11 on 2026-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_threadevent_type_userevent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userevent',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'assign')), fields=('user', 'thread'), name='usrevt_user_thread_assign_uniq'),
        ),
    ]
