# Generated by Django 5.2.11 on 2026-05-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_attachment_message_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='_deprecated_messages',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='_deprecated_mailbox',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='_deprecated_maildomain',
        ),
    ]
