# Generated by Django 5.2.11 on 2026-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_attachment__deprecated_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mime_id',
            field=models.CharField(blank=True, db_index=True, max_length=998, null=True, verbose_name='mime id'),
        ),
    ]
