# Generated by Django 5.2.11 on 2026-06-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_message_mime_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, help_text='Set when processing was permanently abandoned after the retry window; the row is kept for inspection/replay and skipped by the retry sweep.', null=True, verbose_name='abandoned at'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='blob',
            field=models.ForeignKey(blank=True, help_text='Existing blob holding the message bytes (internal mail)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_messages', to='core.blob'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal mailbox-to-mailbox delivery (skips spam checking)', verbose_name='is internal'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='raw_data',
            field=models.BinaryField(blank=True, help_text='Raw email message bytes (external mail; null when backed by blob)', null=True, verbose_name='raw data'),
        ),
        migrations.AddConstraint(
            model_name='inboundmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('blob__isnull', True), ('raw_data__isnull', False)), models.Q(('blob__isnull', False), ('raw_data__isnull', True)), _connector='OR'), name='inboundmessage_exactly_one_source'),
        ),
    ]
