# Generated by Django 5.2.11 on 2026-07-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_inboundmessage_blob_envelope'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to pause this channel without deleting it.', verbose_name='active'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['type', 'is_active'], name='channel_type_active_idx'),
        ),
    ]
