# Generated by Django 5.2.11 on 2026-07-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_inboundmessage_blob_envelope'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='snippet',
            field=models.TextField(blank=True, verbose_name='snippet'),
        ),
    ]
