# Generated by Django 5.2.17 on 2026-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_address_normalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claims',
            field=models.JSONField(blank=True, default=dict, help_text='Claims from the OIDC token.'),
        ),
    ]
