name: Lint and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  COMPOSE_BAKE: true

jobs:

  lint-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create env files
        run: make create-env-files
      - name: Run linting checks
        run: make back-lint


  test-back:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: 1001
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create env files
        run: make create-env-files
      - name: Setup data directories
        run: |
          mkdir -p data/media data/static
          chown -R 1001:1001 data
      - name: Collect static files
        run: make collectstatic
      - name: Create msg-imports bucket
        run: make import-bucket
      - name: Run backend tests
        run: make back-test

  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create env files
        run: make create-env-files
      - name: Install frontend dependencies
        run: make front-install-frozen
      - name: Run frontend tests
        run: make front-test

  lint-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create env files
        run: make create-env-files
      - name: Install frontend dependencies
        run: make front-install-frozen
      - name: Run frontend linting
        run: make front-lint
      - name: Run frontend check
        run: make front-ts-check

  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create env files
        run: make create-env-files
      - name: Install frontend dependencies
        run: make front-install-frozen
      - name: Build frontend
        run: make front-build

  check-api-state:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create env files
        run: make create-env-files
      - name: Install frontend dependencies
        run: make front-install-frozen
      - name: Run API update
        run: make api-update
      - name: Check for changes
        run: |
          git diff --quiet || \
          (echo "API changes detected. Please run 'make api-update' then commit the changes." && exit 1)

  check-changelog:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'noChangeLog') == false &&
      github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch base branch
        run: git fetch origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
      - name: Check that the CHANGELOG has been modified in the current branch
        run: git log --name-only --pretty="" origin/${{ github.event.pull_request.base.ref }}..HEAD | grep CHANGELOG

  lint-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check CHANGELOG max line length
        run: |
          max_line_length=$(cat CHANGELOG.md | grep -Ev "^\[.*\]: https://github.com" | wc -L)
          if [ $max_line_length -ge 80 ]; then
            echo "ERROR: CHANGELOG has lines longer than 80 characters."
            exit 1
          fi

  docker-publish-mta-in:
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
    with:
      image_name: "mta-in"
      context: "src/mta-in"
      target: runtime-prod

  docker-publish-mta-out:
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
    with:
      image_name: "mta-out"
      context: "src/mta-out"
      target: runtime-prod

  docker-publish-socks-proxy:
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
    with:
      image_name: "socks-proxy"
      context: "src/socks-proxy"
